import React from "react";
import BootFormDisplay from "components/Common/BootFormDisplay";
import ElementList from "Admin/ElementList";
import AntMenu from "components/Common/Menu";
import DenseAppBar from "components/Common/AppBar";

const formArray1 = [
  {
    controlId: "formEmail",
    labelText: "Email",
    name: "email",
    controlType: "email",
    placeholder: "test placeholder",
    formText: "We'll never share your email with anyone else.",
  },
];
const adminMenu = [
  {
    _id: "admin0",
    access: [],
    title: "Organization",
    desc: "",
    type: "admin",
    seq: 0,
    comp: "",
    layout: [],
    pid: "",
  },

  {
    _id: "admin1",
    access: [],
    title: "Menu",
    desc: "",
    type: "admin",
    seq: 1,
    comp: "",
    layout: [],
    pid: "",
  },
  {
    _id: "admin2",
    access: [],
    title: "Form",
    desc: "",
    type: "admin",
    seq: 2,
    comp: "",
    layout: [],
    pid: "",
  },
  {
    _id: "admin3",
    access: [],
    title: "System",
    desc: "",
    type: "admin",
    seq: 3,
    comp: "",
    layout: [],
    pid: "",
  },
  {
    _id: "admin0_0",
    access: [],
    title: "Company",
    desc: "",
    type: "admin",
    seq: 0,
    comp: "",
    layout: [],
    pid: "admin0",
  },
  {
    _id: "admin0_1",
    access: [],
    title: "User",
    desc: "",
    type: "admin",
    seq: 1,
    comp: "",
    layout: [],
    pid: "admin0",
  },
  {
    _id: "admin0_2",
    access: [],
    title: "Group",
    desc: "",
    type: "admin",
    seq: 2,
    comp: "",
    layout: [],
    pid: "admin0",
  },
  {
    _id: "admin0_3",
    access: [],
    title: "Organization",
    desc: "",
    type: "admin",
    seq: 3,
    comp: "",
    layout: [],
    pid: "admin0",
  },
  {
    _id: "admin0_4",
    access: [],
    title: "Product/Service",
    desc: "",
    type: "admin",
    seq: 4,
    comp: "",
    layout: [],
    pid: "admin0",
  },
  {
    _id: "admin1_0",
    access: [],
    title: "MenuBuild",
    desc: "",
    type: "admin",
    seq: 0,
    comp: "",
    layout: [],
    pid: "admin1",
  },
  {
    _id: "admin1_1",
    access: [],
    title: "PageBuild",
    desc: "",
    type: "admin",
    seq: 1,
    comp: "",
    layout: [],
    pid: "admin1",
  },
  {
    _id: "admin3_0",
    access: [],
    title: "DataBase",
    desc: "",
    type: "admin",
    seq: 0,
    comp: "",
    layout: [],
    pid: "admin3",
  },
  {
    _id: "admin3_1",
    access: [],
    title: "Miscellaneous",
    desc: "",
    type: "admin",
    seq: 1,
    comp: "",
    layout: [],
    pid: "admin3",
  },
];

const adminMenu1 = [
  {
    access: [],
    title: "Organization",
    desc: "",
    type: "admin",
    seq: 0,
    comp: "",
    layout: [],
    pid: "",
  },

  {
    access: [],
    title: "Menu",
    desc: "",
    type: "admin",
    seq: 1,
    comp: "",
    layout: [],
    pid: "",
  },
  {
    access: [],
    title: "Form",
    desc: "",
    type: "admin",
    seq: 2,
    comp: "",
    layout: [],
    pid: "",
  },
  {
    access: [],
    title: "System",
    desc: "",
    type: "admin",
    seq: 3,
    comp: "",
    layout: [],
    pid: "",
  },
  {
    access: [],
    title: "Company",
    desc: "",
    type: "admin",
    seq: 0,
    comp: "",
    layout: [],
    pid: "5e8ed662bdb50363914263af",
  },
  {
    access: [],
    title: "User",
    desc: "",
    type: "admin",
    seq: 1,
    comp: "",
    layout: [],
    pid: "5e8ed662bdb50363914263af",
  },
  {
    access: [],
    title: "Group",
    desc: "",
    type: "admin",
    seq: 2,
    comp: "",
    layout: [],
    pid: "5e8ed662bdb50363914263af",
  },
  {
    access: [],
    title: "Organization",
    desc: "",
    type: "admin",
    seq: 3,
    comp: "",
    layout: [],
    pid: "5e8ed662bdb50363914263af",
  },
  {
    access: [],
    title: "Product/Service",
    desc: "",
    type: "admin",
    seq: 4,
    comp: "",
    layout: [],
    pid: "5e8ed662bdb50363914263af",
  },
  {
    access: [],
    title: "MenuBuild",
    desc: "",
    type: "admin",
    seq: 0,
    comp: "",
    layout: [],
    pid: "5e8ed662bdb50363914263b0",
  },
  {
    access: [],
    title: "PageBuild",
    desc: "",
    type: "admin",
    seq: 1,
    comp: "",
    layout: [],
    pid: "5e8ed662bdb50363914263b0",
  },
  {
    _id: "admin3_0",
    access: [],
    title: "DataBase",
    desc: "",
    type: "admin",
    seq: 0,
    comp: "",
    layout: [],
    pid: "admin3",
  },
  {
    _id: "admin3_1",
    access: [],
    title: "Miscellaneous",
    desc: "",
    type: "admin",
    seq: 1,
    comp: "",
    layout: [],
    pid: "admin3",
  },
];
const Admin = () => {
  // const pathname = encodeURIComponent(window.location.pathname);

  // return <ElementList eltype={["password", "email"]} />;
  return (
    <DenseAppBar title={"Admin"}>
      <AntMenu />
    </DenseAppBar>
  );
};

export default Admin;
